language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install nose2 flake8 pylint codecov
    - npm install
    - ls node_modules/\@jpmorganchase/perspective/build
    - pwd
    - ln -s ../../timkpaine ../../../timkpaine
    - npm run build

script: 
  - make test
  - npm run test

after_success:
    - codecov --token f1584ece-92aa-4be7-b6ae-89c02a19af16

branches:
  only:
  - master

notifications:
  email: false
