language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

sudo: true

install:
    - pip install -r requirements.txt
    - pip install nose2 flake8 pylint codecov
    - npm install
    - mkdir -p ~/timkpaine/hedgeme/node_modules
    - cp -r node_modules/* ~/timkpaine/hedgeme/node_modules
    - npm run build

script: 
  - make test
  - npm run test

after_success:
    - codecov --token f1584ece-92aa-4be7-b6ae-89c02a19af16

branches:
  only:
  - master

notifications:
  email: false
